# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22776845ed7f5e5581eaf6de7522a070e21ae6be5364583fb831acfe1cb62773ccf8ba8bb36172bf657e9076fcc19531cff3ab09f0b146e1cf82d90d830a2841

test:
  secret_key_base: 2145a5991b2ddd218670f0be2a8e11b18750fcf116b983aff7d32bcb695d69207a731eadef5e904cbc40fc49063d75f592798c030399815089ab08f1ff964268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
