# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bf1a387206c6810cd96bb914ab4d91115205f784e2edc3dec1ef966943303f64d7c62912844a71c94702f1836a6643fc2c3b56c268a8c5f39401e2d770d127a

test:
  secret_key_base: 5366bb8447e8d34673cf9437af2fa8b2ea38e57aa5e4a6f226810f5c4e6f7ea6f65fb789712a45874c96ae83b500acf62075b27f4273178a5f88db8867635339

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
